// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ROV_Image.proto

package org.metamorarobotics.image;

public final class ROVImage {
  private ROVImage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SerializedMatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.metamorarobotics.image.SerializedMat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 width = 1;</code>
     */
    boolean hasWidth();
    /**
     * <code>required int32 width = 1;</code>
     */
    int getWidth();

    /**
     * <code>required int32 height = 2;</code>
     */
    boolean hasHeight();
    /**
     * <code>required int32 height = 2;</code>
     */
    int getHeight();

    /**
     * <code>required .org.metamorarobotics.image.SerializedMat.TypeEnum type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required .org.metamorarobotics.image.SerializedMat.TypeEnum type = 3;</code>
     */
    org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum getType();

    /**
     * <code>required bytes data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code org.metamorarobotics.image.SerializedMat}
   */
  public static final class SerializedMat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.metamorarobotics.image.SerializedMat)
      SerializedMatOrBuilder {
    // Use SerializedMat.newBuilder() to construct.
    private SerializedMat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SerializedMat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SerializedMat defaultInstance;
    public static SerializedMat getDefaultInstance() {
      return defaultInstance;
    }

    public SerializedMat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SerializedMat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              width_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              height_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum value = org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.metamorarobotics.image.ROVImage.internal_static_org_metamorarobotics_image_SerializedMat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.metamorarobotics.image.ROVImage.internal_static_org_metamorarobotics_image_SerializedMat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.metamorarobotics.image.ROVImage.SerializedMat.class, org.metamorarobotics.image.ROVImage.SerializedMat.Builder.class);
    }

    public static com.google.protobuf.Parser<SerializedMat> PARSER =
        new com.google.protobuf.AbstractParser<SerializedMat>() {
      public SerializedMat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SerializedMat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SerializedMat> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.metamorarobotics.image.SerializedMat.TypeEnum}
     */
    public enum TypeEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RGB = 1;</code>
       */
      RGB(0, 1),
      /**
       * <code>GRAY = 2;</code>
       */
      GRAY(1, 2),
      ;

      /**
       * <code>RGB = 1;</code>
       */
      public static final int RGB_VALUE = 1;
      /**
       * <code>GRAY = 2;</code>
       */
      public static final int GRAY_VALUE = 2;


      public final int getNumber() { return value; }

      public static TypeEnum valueOf(int value) {
        switch (value) {
          case 1: return RGB;
          case 2: return GRAY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TypeEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<TypeEnum>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TypeEnum>() {
              public TypeEnum findValueByNumber(int number) {
                return TypeEnum.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.metamorarobotics.image.ROVImage.SerializedMat.getDescriptor().getEnumTypes().get(0);
      }

      private static final TypeEnum[] VALUES = values();

      public static TypeEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private TypeEnum(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.metamorarobotics.image.SerializedMat.TypeEnum)
    }

    private int bitField0_;
    public static final int WIDTH_FIELD_NUMBER = 1;
    private int width_;
    /**
     * <code>required int32 width = 1;</code>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 width = 1;</code>
     */
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private int height_;
    /**
     * <code>required int32 height = 2;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 height = 2;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum type_;
    /**
     * <code>required .org.metamorarobotics.image.SerializedMat.TypeEnum type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .org.metamorarobotics.image.SerializedMat.TypeEnum type = 3;</code>
     */
    public org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum getType() {
      return type_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      width_ = 0;
      height_ = 0;
      type_ = org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum.RGB;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, width_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, height_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, width_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, height_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.metamorarobotics.image.ROVImage.SerializedMat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.metamorarobotics.image.ROVImage.SerializedMat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.metamorarobotics.image.ROVImage.SerializedMat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.metamorarobotics.image.ROVImage.SerializedMat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.metamorarobotics.image.ROVImage.SerializedMat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.metamorarobotics.image.ROVImage.SerializedMat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.metamorarobotics.image.ROVImage.SerializedMat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.metamorarobotics.image.ROVImage.SerializedMat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.metamorarobotics.image.ROVImage.SerializedMat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.metamorarobotics.image.ROVImage.SerializedMat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.metamorarobotics.image.ROVImage.SerializedMat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.metamorarobotics.image.SerializedMat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.metamorarobotics.image.SerializedMat)
        org.metamorarobotics.image.ROVImage.SerializedMatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.metamorarobotics.image.ROVImage.internal_static_org_metamorarobotics_image_SerializedMat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.metamorarobotics.image.ROVImage.internal_static_org_metamorarobotics_image_SerializedMat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.metamorarobotics.image.ROVImage.SerializedMat.class, org.metamorarobotics.image.ROVImage.SerializedMat.Builder.class);
      }

      // Construct using org.metamorarobotics.image.ROVImage.SerializedMat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum.RGB;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.metamorarobotics.image.ROVImage.internal_static_org_metamorarobotics_image_SerializedMat_descriptor;
      }

      public org.metamorarobotics.image.ROVImage.SerializedMat getDefaultInstanceForType() {
        return org.metamorarobotics.image.ROVImage.SerializedMat.getDefaultInstance();
      }

      public org.metamorarobotics.image.ROVImage.SerializedMat build() {
        org.metamorarobotics.image.ROVImage.SerializedMat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.metamorarobotics.image.ROVImage.SerializedMat buildPartial() {
        org.metamorarobotics.image.ROVImage.SerializedMat result = new org.metamorarobotics.image.ROVImage.SerializedMat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.metamorarobotics.image.ROVImage.SerializedMat) {
          return mergeFrom((org.metamorarobotics.image.ROVImage.SerializedMat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.metamorarobotics.image.ROVImage.SerializedMat other) {
        if (other == org.metamorarobotics.image.ROVImage.SerializedMat.getDefaultInstance()) return this;
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.metamorarobotics.image.ROVImage.SerializedMat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.metamorarobotics.image.ROVImage.SerializedMat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int width_ ;
      /**
       * <code>required int32 width = 1;</code>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 width = 1;</code>
       */
      public int getWidth() {
        return width_;
      }
      /**
       * <code>required int32 width = 1;</code>
       */
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000001;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 width = 1;</code>
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>required int32 height = 2;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 height = 2;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>required int32 height = 2;</code>
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000002;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 height = 2;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        height_ = 0;
        onChanged();
        return this;
      }

      private org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum type_ = org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum.RGB;
      /**
       * <code>required .org.metamorarobotics.image.SerializedMat.TypeEnum type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .org.metamorarobotics.image.SerializedMat.TypeEnum type = 3;</code>
       */
      public org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum getType() {
        return type_;
      }
      /**
       * <code>required .org.metamorarobotics.image.SerializedMat.TypeEnum type = 3;</code>
       */
      public Builder setType(org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .org.metamorarobotics.image.SerializedMat.TypeEnum type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = org.metamorarobotics.image.ROVImage.SerializedMat.TypeEnum.RGB;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.metamorarobotics.image.SerializedMat)
    }

    static {
      defaultInstance = new SerializedMat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.metamorarobotics.image.SerializedMat)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_metamorarobotics_image_SerializedMat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_metamorarobotics_image_SerializedMat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ROV_Image.proto\022\032org.metamorarobotics." +
      "image\"\235\001\n\rSerializedMat\022\r\n\005width\030\001 \002(\005\022\016" +
      "\n\006height\030\002 \002(\005\022@\n\004type\030\003 \002(\01622.org.metam" +
      "orarobotics.image.SerializedMat.TypeEnum" +
      "\022\014\n\004data\030\004 \002(\014\"\035\n\010TypeEnum\022\007\n\003RGB\020\001\022\010\n\004G" +
      "RAY\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_metamorarobotics_image_SerializedMat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_metamorarobotics_image_SerializedMat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_metamorarobotics_image_SerializedMat_descriptor,
        new java.lang.String[] { "Width", "Height", "Type", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
